// Generated by tools/gen_layout_check.py from Khronos vk.xml (VK_HEADER_VERSION 365,
// sha256 e0af19419d8fe3d4de78fc872891571d5eadc9e78df1b45dad7ece5b8b400acf). Do not edit: a mismatch with ffi.rs fails the build.
#![allow(dead_code)]
use crate::ffi::*;
use ash::vk;
use core::ffi::c_void;
use core::mem::{align_of, offset_of, size_of};

const fn same(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    let mut i = 0;
    while i < a.len() { if a[i] != b[i] { return false; } i += 1; }
    true
}

// VkPhysicalDevicePresentTimingFeaturesEXT
const _: () = assert!(size_of::<PhysicalDevicePresentTimingFeaturesEXT>() == 32 && align_of::<PhysicalDevicePresentTimingFeaturesEXT>() == 8);
const _: () = assert!(offset_of!(PhysicalDevicePresentTimingFeaturesEXT, s_type) == 0);
const _: () = assert!(offset_of!(PhysicalDevicePresentTimingFeaturesEXT, p_next) == 8);
const _: () = assert!(offset_of!(PhysicalDevicePresentTimingFeaturesEXT, present_timing) == 16);
const _: () = assert!(offset_of!(PhysicalDevicePresentTimingFeaturesEXT, present_at_absolute_time) == 20);
const _: () = assert!(offset_of!(PhysicalDevicePresentTimingFeaturesEXT, present_at_relative_time) == 24);
#[allow(non_snake_case)]
fn _types_PhysicalDevicePresentTimingFeaturesEXT(s: &PhysicalDevicePresentTimingFeaturesEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &vk::Bool32 = &s.present_timing;
    let _: &vk::Bool32 = &s.present_at_absolute_time;
    let _: &vk::Bool32 = &s.present_at_relative_time;
}

// VkPresentTimingSurfaceCapabilitiesEXT
const _: () = assert!(size_of::<PresentTimingSurfaceCapabilitiesEXT>() == 32 && align_of::<PresentTimingSurfaceCapabilitiesEXT>() == 8);
const _: () = assert!(offset_of!(PresentTimingSurfaceCapabilitiesEXT, s_type) == 0);
const _: () = assert!(offset_of!(PresentTimingSurfaceCapabilitiesEXT, p_next) == 8);
const _: () = assert!(offset_of!(PresentTimingSurfaceCapabilitiesEXT, present_timing_supported) == 16);
const _: () = assert!(offset_of!(PresentTimingSurfaceCapabilitiesEXT, present_at_absolute_time_supported) == 20);
const _: () = assert!(offset_of!(PresentTimingSurfaceCapabilitiesEXT, present_at_relative_time_supported) == 24);
const _: () = assert!(offset_of!(PresentTimingSurfaceCapabilitiesEXT, present_stage_queries) == 28);
#[allow(non_snake_case)]
fn _types_PresentTimingSurfaceCapabilitiesEXT(s: &PresentTimingSurfaceCapabilitiesEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &vk::Bool32 = &s.present_timing_supported;
    let _: &vk::Bool32 = &s.present_at_absolute_time_supported;
    let _: &vk::Bool32 = &s.present_at_relative_time_supported;
    let _: &u32 = &s.present_stage_queries;
}

// VkSwapchainCalibratedTimestampInfoEXT
const _: () = assert!(size_of::<SwapchainCalibratedTimestampInfoEXT>() == 40 && align_of::<SwapchainCalibratedTimestampInfoEXT>() == 8);
const _: () = assert!(offset_of!(SwapchainCalibratedTimestampInfoEXT, s_type) == 0);
const _: () = assert!(offset_of!(SwapchainCalibratedTimestampInfoEXT, p_next) == 8);
const _: () = assert!(offset_of!(SwapchainCalibratedTimestampInfoEXT, swapchain) == 16);
const _: () = assert!(offset_of!(SwapchainCalibratedTimestampInfoEXT, present_stage) == 24);
const _: () = assert!(offset_of!(SwapchainCalibratedTimestampInfoEXT, time_domain_id) == 32);
#[allow(non_snake_case)]
fn _types_SwapchainCalibratedTimestampInfoEXT(s: &SwapchainCalibratedTimestampInfoEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*const c_void = &s.p_next;
    let _: &vk::SwapchainKHR = &s.swapchain;
    let _: &u32 = &s.present_stage;
    let _: &u64 = &s.time_domain_id;
}

// VkSwapchainTimingPropertiesEXT
const _: () = assert!(size_of::<SwapchainTimingPropertiesEXT>() == 32 && align_of::<SwapchainTimingPropertiesEXT>() == 8);
const _: () = assert!(offset_of!(SwapchainTimingPropertiesEXT, s_type) == 0);
const _: () = assert!(offset_of!(SwapchainTimingPropertiesEXT, p_next) == 8);
const _: () = assert!(offset_of!(SwapchainTimingPropertiesEXT, refresh_duration) == 16);
const _: () = assert!(offset_of!(SwapchainTimingPropertiesEXT, refresh_interval) == 24);
#[allow(non_snake_case)]
fn _types_SwapchainTimingPropertiesEXT(s: &SwapchainTimingPropertiesEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &u64 = &s.refresh_duration;
    let _: &u64 = &s.refresh_interval;
}

// VkSwapchainTimeDomainPropertiesEXT
const _: () = assert!(size_of::<SwapchainTimeDomainPropertiesEXT>() == 40 && align_of::<SwapchainTimeDomainPropertiesEXT>() == 8);
const _: () = assert!(offset_of!(SwapchainTimeDomainPropertiesEXT, s_type) == 0);
const _: () = assert!(offset_of!(SwapchainTimeDomainPropertiesEXT, p_next) == 8);
const _: () = assert!(offset_of!(SwapchainTimeDomainPropertiesEXT, time_domain_count) == 16);
const _: () = assert!(offset_of!(SwapchainTimeDomainPropertiesEXT, p_time_domains) == 24);
const _: () = assert!(offset_of!(SwapchainTimeDomainPropertiesEXT, p_time_domain_ids) == 32);
#[allow(non_snake_case)]
fn _types_SwapchainTimeDomainPropertiesEXT(s: &SwapchainTimeDomainPropertiesEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &u32 = &s.time_domain_count;
    let _: &*mut vk::TimeDomainKHR = &s.p_time_domains;
    let _: &*mut u64 = &s.p_time_domain_ids;
}

// VkPastPresentationTimingInfoEXT
const _: () = assert!(size_of::<PastPresentationTimingInfoEXT>() == 32 && align_of::<PastPresentationTimingInfoEXT>() == 8);
const _: () = assert!(offset_of!(PastPresentationTimingInfoEXT, s_type) == 0);
const _: () = assert!(offset_of!(PastPresentationTimingInfoEXT, p_next) == 8);
const _: () = assert!(offset_of!(PastPresentationTimingInfoEXT, flags) == 16);
const _: () = assert!(offset_of!(PastPresentationTimingInfoEXT, swapchain) == 24);
#[allow(non_snake_case)]
fn _types_PastPresentationTimingInfoEXT(s: &PastPresentationTimingInfoEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*const c_void = &s.p_next;
    let _: &u32 = &s.flags;
    let _: &vk::SwapchainKHR = &s.swapchain;
}

// VkPastPresentationTimingPropertiesEXT
const _: () = assert!(size_of::<PastPresentationTimingPropertiesEXT>() == 48 && align_of::<PastPresentationTimingPropertiesEXT>() == 8);
const _: () = assert!(offset_of!(PastPresentationTimingPropertiesEXT, s_type) == 0);
const _: () = assert!(offset_of!(PastPresentationTimingPropertiesEXT, p_next) == 8);
const _: () = assert!(offset_of!(PastPresentationTimingPropertiesEXT, timing_properties_counter) == 16);
const _: () = assert!(offset_of!(PastPresentationTimingPropertiesEXT, time_domains_counter) == 24);
const _: () = assert!(offset_of!(PastPresentationTimingPropertiesEXT, presentation_timing_count) == 32);
const _: () = assert!(offset_of!(PastPresentationTimingPropertiesEXT, p_presentation_timings) == 40);
#[allow(non_snake_case)]
fn _types_PastPresentationTimingPropertiesEXT(s: &PastPresentationTimingPropertiesEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &u64 = &s.timing_properties_counter;
    let _: &u64 = &s.time_domains_counter;
    let _: &u32 = &s.presentation_timing_count;
    let _: &*mut PastPresentationTimingEXT = &s.p_presentation_timings;
}

// VkPastPresentationTimingEXT
const _: () = assert!(size_of::<PastPresentationTimingEXT>() == 72 && align_of::<PastPresentationTimingEXT>() == 8);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, s_type) == 0);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, p_next) == 8);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, present_id) == 16);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, target_time) == 24);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, present_stage_count) == 32);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, p_present_stages) == 40);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, time_domain) == 48);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, time_domain_id) == 56);
const _: () = assert!(offset_of!(PastPresentationTimingEXT, report_complete) == 64);
#[allow(non_snake_case)]
fn _types_PastPresentationTimingEXT(s: &PastPresentationTimingEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &u64 = &s.present_id;
    let _: &u64 = &s.target_time;
    let _: &u32 = &s.present_stage_count;
    let _: &*mut PresentStageTimeEXT = &s.p_present_stages;
    let _: &vk::TimeDomainKHR = &s.time_domain;
    let _: &u64 = &s.time_domain_id;
    let _: &vk::Bool32 = &s.report_complete;
}

// VkPresentTimingsInfoEXT
const _: () = assert!(size_of::<PresentTimingsInfoEXT>() == 32 && align_of::<PresentTimingsInfoEXT>() == 8);
const _: () = assert!(offset_of!(PresentTimingsInfoEXT, s_type) == 0);
const _: () = assert!(offset_of!(PresentTimingsInfoEXT, p_next) == 8);
const _: () = assert!(offset_of!(PresentTimingsInfoEXT, swapchain_count) == 16);
const _: () = assert!(offset_of!(PresentTimingsInfoEXT, p_timing_infos) == 24);
#[allow(non_snake_case)]
fn _types_PresentTimingsInfoEXT(s: &PresentTimingsInfoEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*const c_void = &s.p_next;
    let _: &u32 = &s.swapchain_count;
    let _: &*const PresentTimingInfoEXT = &s.p_timing_infos;
}

// VkPresentTimingInfoEXT
const _: () = assert!(size_of::<PresentTimingInfoEXT>() == 48 && align_of::<PresentTimingInfoEXT>() == 8);
const _: () = assert!(offset_of!(PresentTimingInfoEXT, s_type) == 0);
const _: () = assert!(offset_of!(PresentTimingInfoEXT, p_next) == 8);
const _: () = assert!(offset_of!(PresentTimingInfoEXT, flags) == 16);
const _: () = assert!(offset_of!(PresentTimingInfoEXT, target_time) == 24);
const _: () = assert!(offset_of!(PresentTimingInfoEXT, time_domain_id) == 32);
const _: () = assert!(offset_of!(PresentTimingInfoEXT, present_stage_queries) == 40);
const _: () = assert!(offset_of!(PresentTimingInfoEXT, target_time_domain_present_stage) == 44);
#[allow(non_snake_case)]
fn _types_PresentTimingInfoEXT(s: &PresentTimingInfoEXT) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*const c_void = &s.p_next;
    let _: &u32 = &s.flags;
    let _: &u64 = &s.target_time;
    let _: &u64 = &s.time_domain_id;
    let _: &u32 = &s.present_stage_queries;
    let _: &u32 = &s.target_time_domain_present_stage;
}

// VkPresentStageTimeEXT
const _: () = assert!(size_of::<PresentStageTimeEXT>() == 16 && align_of::<PresentStageTimeEXT>() == 8);
const _: () = assert!(offset_of!(PresentStageTimeEXT, stage) == 0);
const _: () = assert!(offset_of!(PresentStageTimeEXT, time) == 8);
#[allow(non_snake_case)]
fn _types_PresentStageTimeEXT(s: &PresentStageTimeEXT) {
    let _: &u32 = &s.stage;
    let _: &u64 = &s.time;
}

// VkPhysicalDevicePresentId2FeaturesKHR
const _: () = assert!(size_of::<PhysicalDevicePresentId2FeaturesKHR>() == 24 && align_of::<PhysicalDevicePresentId2FeaturesKHR>() == 8);
const _: () = assert!(offset_of!(PhysicalDevicePresentId2FeaturesKHR, s_type) == 0);
const _: () = assert!(offset_of!(PhysicalDevicePresentId2FeaturesKHR, p_next) == 8);
const _: () = assert!(offset_of!(PhysicalDevicePresentId2FeaturesKHR, present_id2) == 16);
#[allow(non_snake_case)]
fn _types_PhysicalDevicePresentId2FeaturesKHR(s: &PhysicalDevicePresentId2FeaturesKHR) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &vk::Bool32 = &s.present_id2;
}

// VkSurfaceCapabilitiesPresentId2KHR
const _: () = assert!(size_of::<SurfaceCapabilitiesPresentId2KHR>() == 24 && align_of::<SurfaceCapabilitiesPresentId2KHR>() == 8);
const _: () = assert!(offset_of!(SurfaceCapabilitiesPresentId2KHR, s_type) == 0);
const _: () = assert!(offset_of!(SurfaceCapabilitiesPresentId2KHR, p_next) == 8);
const _: () = assert!(offset_of!(SurfaceCapabilitiesPresentId2KHR, present_id2_supported) == 16);
#[allow(non_snake_case)]
fn _types_SurfaceCapabilitiesPresentId2KHR(s: &SurfaceCapabilitiesPresentId2KHR) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*mut c_void = &s.p_next;
    let _: &vk::Bool32 = &s.present_id2_supported;
}

// VkPresentId2KHR
const _: () = assert!(size_of::<PresentId2KHR>() == 32 && align_of::<PresentId2KHR>() == 8);
const _: () = assert!(offset_of!(PresentId2KHR, s_type) == 0);
const _: () = assert!(offset_of!(PresentId2KHR, p_next) == 8);
const _: () = assert!(offset_of!(PresentId2KHR, swapchain_count) == 16);
const _: () = assert!(offset_of!(PresentId2KHR, p_present_ids) == 24);
#[allow(non_snake_case)]
fn _types_PresentId2KHR(s: &PresentId2KHR) {
    let _: &vk::StructureType = &s.s_type;
    let _: &*const c_void = &s.p_next;
    let _: &u32 = &s.swapchain_count;
    let _: &*const u64 = &s.p_present_ids;
}

// sType values (1000000000 + (extension number - 1) * 1000 + offset)
const _: () = assert!(ST_PHYSICAL_DEVICE_PRESENT_TIMING_FEATURES_EXT == 1000208000);
const _: () = assert!(ST_PRESENT_TIMING_SURFACE_CAPABILITIES_EXT == 1000208008);
const _: () = assert!(ST_SWAPCHAIN_CALIBRATED_TIMESTAMP_INFO_EXT == 1000208009);
const _: () = assert!(ST_SWAPCHAIN_TIMING_PROPERTIES_EXT == 1000208001);
const _: () = assert!(ST_SWAPCHAIN_TIME_DOMAIN_PROPERTIES_EXT == 1000208002);
const _: () = assert!(ST_PAST_PRESENTATION_TIMING_INFO_EXT == 1000208005);
const _: () = assert!(ST_PAST_PRESENTATION_TIMING_PROPERTIES_EXT == 1000208006);
const _: () = assert!(ST_PAST_PRESENTATION_TIMING_EXT == 1000208007);
const _: () = assert!(ST_PRESENT_TIMINGS_INFO_EXT == 1000208003);
const _: () = assert!(ST_PRESENT_TIMING_INFO_EXT == 1000208004);
const _: () = assert!(ST_PHYSICAL_DEVICE_PRESENT_ID_2_FEATURES_KHR == 1000479002);
const _: () = assert!(ST_SURFACE_CAPABILITIES_PRESENT_ID_2_KHR == 1000479000);
const _: () = assert!(ST_PRESENT_ID_2_KHR == 1000479001);
// Enum and bit values
const _: () = assert!(TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT == 1000208000);
const _: () = assert!(TIME_DOMAIN_SWAPCHAIN_LOCAL_EXT == 1000208001);
const _: () = assert!(ERROR_PRESENT_TIMING_QUEUE_FULL_EXT == -1000208000);
const _: () = assert!(SWAPCHAIN_CREATE_PRESENT_TIMING_BIT_EXT == 512);
const _: () = assert!(SWAPCHAIN_CREATE_PRESENT_ID_2_BIT_KHR == 64);
const _: () = assert!(PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT == 1);
const _: () = assert!(PRESENT_STAGE_REQUEST_DEQUEUED_BIT_EXT == 2);
const _: () = assert!(PRESENT_STAGE_IMAGE_FIRST_PIXEL_OUT_BIT_EXT == 4);
const _: () = assert!(PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT == 8);
// Command signatures
const _: Option<unsafe extern "system" fn(vk::Device, vk::SwapchainKHR, u32) -> vk::Result> = None::<PfnSetSwapchainPresentTimingQueueSizeEXT>;
const _: () = assert!(same(COMMAND_NAMES[0].to_bytes(), b"vkSetSwapchainPresentTimingQueueSizeEXT"));
const _: Option<unsafe extern "system" fn(vk::Device, vk::SwapchainKHR, *mut SwapchainTimingPropertiesEXT, *mut u64) -> vk::Result> = None::<PfnGetSwapchainTimingPropertiesEXT>;
const _: () = assert!(same(COMMAND_NAMES[1].to_bytes(), b"vkGetSwapchainTimingPropertiesEXT"));
const _: Option<unsafe extern "system" fn(vk::Device, vk::SwapchainKHR, *mut SwapchainTimeDomainPropertiesEXT, *mut u64) -> vk::Result> = None::<PfnGetSwapchainTimeDomainPropertiesEXT>;
const _: () = assert!(same(COMMAND_NAMES[2].to_bytes(), b"vkGetSwapchainTimeDomainPropertiesEXT"));
const _: Option<unsafe extern "system" fn(vk::Device, *const PastPresentationTimingInfoEXT, *mut PastPresentationTimingPropertiesEXT) -> vk::Result> = None::<PfnGetPastPresentationTimingEXT>;
const _: () = assert!(same(COMMAND_NAMES[3].to_bytes(), b"vkGetPastPresentationTimingEXT"));
// Extension names
const _: () = assert!(same(EXT_PRESENT_TIMING_NAME.to_bytes(), b"VK_EXT_present_timing"));
const _: () = assert!(same(KHR_PRESENT_ID2_NAME.to_bytes(), b"VK_KHR_present_id2"));
