"""Spike S part 2: generate src/layout_check.rs from Khronos vk.xml.

For every struct, constant, command and extension name that src/ffi.rs writes by hand, this
emits compile-time assertions whose expected values come from vk.xml alone: each struct's size,
alignment, and every member's offset and Rust type (x86_64 C layout); each enum or bit value;
each command's full signature; each extension name. A mismatch fails `cargo build`.

usage: python3 gen_layout_check.py <vk.xml> <out.rs>
"""
import hashlib
import re
import sys
import xml.etree.ElementTree as ET

STRUCTS = [
    "VkPhysicalDevicePresentTimingFeaturesEXT", "VkPresentTimingSurfaceCapabilitiesEXT",
    "VkSwapchainCalibratedTimestampInfoEXT", "VkSwapchainTimingPropertiesEXT",
    "VkSwapchainTimeDomainPropertiesEXT", "VkPastPresentationTimingInfoEXT",
    "VkPastPresentationTimingPropertiesEXT", "VkPastPresentationTimingEXT",
    "VkPresentTimingsInfoEXT", "VkPresentTimingInfoEXT", "VkPresentStageTimeEXT",
    "VkPhysicalDevicePresentId2FeaturesKHR", "VkSurfaceCapabilitiesPresentId2KHR", "VkPresentId2KHR",
]
CONSTANTS = [  # Rust name; the vk.xml name is "VK_" + this
    "TIME_DOMAIN_PRESENT_STAGE_LOCAL_EXT", "TIME_DOMAIN_SWAPCHAIN_LOCAL_EXT",
    "ERROR_PRESENT_TIMING_QUEUE_FULL_EXT", "SWAPCHAIN_CREATE_PRESENT_TIMING_BIT_EXT",
    "SWAPCHAIN_CREATE_PRESENT_ID_2_BIT_KHR", "PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT",
    "PRESENT_STAGE_REQUEST_DEQUEUED_BIT_EXT", "PRESENT_STAGE_IMAGE_FIRST_PIXEL_OUT_BIT_EXT",
    "PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT",
]
COMMANDS = ["vkSetSwapchainPresentTimingQueueSizeEXT", "vkGetSwapchainTimingPropertiesEXT",
            "vkGetSwapchainTimeDomainPropertiesEXT", "vkGetPastPresentationTimingEXT"]
EXTENSIONS = {"EXT_PRESENT_TIMING_NAME": "VK_EXT_present_timing", "KHR_PRESENT_ID2_NAME": "VK_KHR_present_id2"}

RUST = {"uint32_t": "u32", "uint64_t": "u64", "int32_t": "i32", "void": "c_void",
        "VkBool32": "vk::Bool32", "VkStructureType": "vk::StructureType", "VkResult": "vk::Result",
        "VkTimeDomainKHR": "vk::TimeDomainKHR", "VkDevice": "vk::Device", "VkSwapchainKHR": "vk::SwapchainKHR"}
SCALAR = {"uint32_t": 4, "int32_t": 4, "uint64_t": 8}


def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def main(xml_path, out_path):
    raw = open(xml_path, "rb").read()
    root = ET.fromstring(raw)
    types = {t.get("name") or t.findtext("name"): t for t in root.find("types").findall("type")}
    exts = {e.get("name"): e for e in root.iter("extension")}
    header = re.search(r"VK_HEADER_VERSION</name> (\d+)", raw.decode()).group(1)

    def kind(name):
        t = types.get(name)
        return None if t is None else t.get("category")

    def size_align(base, ptr):
        if ptr or base in ("VkDevice",):
            return 8, 8
        if base in SCALAR:
            return SCALAR[base], SCALAR[base]
        k = kind(base)
        if k in ("enum", "bitmask") or base in ("VkBool32", "VkFlags"):
            return 4, 4
        if k == "handle":  # non-dispatchable handles are 64-bit on every platform
            return 8, 8
        raise SystemExit(f"no size rule for {base}")

    def rust_type(base, ptr, const):
        if base in RUST:
            r = RUST[base]
        elif kind(base) == "bitmask":
            r = "u32"  # ffi.rs uses plain u32 for VkFlags typedefs
        elif base in STRUCTS:
            r = base[2:]
        else:
            raise SystemExit(f"no Rust type for {base}")
        return f"*{'const' if const else 'mut'} {r}" if ptr else r

    def member(m):
        text = "".join(m.itertext())
        base = m.find("type").text
        ptr = text.count("*")
        assert ptr <= 1, text
        return m.find("name").text, base, ptr == 1, text.strip().startswith("const")

    out = [f"// Generated by tools/gen_layout_check.py from Khronos vk.xml (VK_HEADER_VERSION {header},",
           f"// sha256 {hashlib.sha256(raw).hexdigest()}). Do not edit: a mismatch with ffi.rs fails the build.",
           "#![allow(dead_code)]", "use crate::ffi::*;", "use ash::vk;", "use core::ffi::c_void;",
           "use core::mem::{align_of, offset_of, size_of};", "",
           "const fn same(a: &[u8], b: &[u8]) -> bool {",
           "    if a.len() != b.len() { return false; }",
           "    let mut i = 0;",
           "    while i < a.len() { if a[i] != b[i] { return false; } i += 1; }",
           "    true", "}", ""]
    stypes = {}
    for s in STRUCTS:
        rs, offset, align = s[2:], 0, 1
        checks, typechecks = [], []
        for m in types[s].findall("member"):
            name, base, ptr, const = member(m)
            sz, al = size_align(base, ptr)
            offset = (offset + al - 1) // al * al
            align = max(align, al)
            f = snake(name)
            checks.append(f"const _: () = assert!(offset_of!({rs}, {f}) == {offset});")
            typechecks.append(f"    let _: &{rust_type(base, ptr, const)} = &s.{f};")
            if name == "sType":
                stypes[m.get("values")] = s
            offset += sz
        size = (offset + align - 1) // align * align
        out.append(f"// {s}")
        out.append(f"const _: () = assert!(size_of::<{rs}>() == {size} && align_of::<{rs}>() == {align});")
        out += checks
        out.append(f"#[allow(non_snake_case)]\nfn _types_{rs}(s: &{rs}) {{")
        out += typechecks
        out += ["}", ""]

    def value(name):
        for e in root.iter("enum"):
            if e.get("name") != name:
                continue
            if e.get("alias"):
                return value(e.get("alias"))
            if e.get("value") is not None:
                v = e.get("value")
                return int(v, 16) if v.startswith("0x") else int(v)
            if e.get("bitpos") is not None:
                return 1 << int(e.get("bitpos"))
            if e.get("offset") is not None:
                number = e.get("extnumber")
                if number is None:
                    owner = next(x for x in exts.values() if e in list(x.iter("enum")))
                    number = owner.get("number")
                v = 1000000000 + (int(number) - 1) * 1000 + int(e.get("offset"))
                return -v if e.get("dir") == "-" else v
        raise SystemExit(f"{name} not in vk.xml")

    out.append("// sType values (1000000000 + (extension number - 1) * 1000 + offset)")
    for st in stypes:
        out.append(f"const _: () = assert!(ST_{st[len('VK_STRUCTURE_TYPE_'):]} == {value(st)});")
    out.append("// Enum and bit values")
    for c in CONSTANTS:
        out.append(f"const _: () = assert!({c} == {value('VK_' + c)});")
    out.append("// Command signatures")
    for c in COMMANDS:
        cmd = next(x for x in root.iter("command") if x.findtext("proto/name") == c)
        params = [rust_type(*member(p)[1:]) for p in cmd.findall("param")]
        ret = RUST[cmd.find("proto/type").text]
        out.append(f"const _: Option<unsafe extern \"system\" fn({', '.join(params)}) -> {ret}> = None::<Pfn{c[2:]}>;")
        out.append(f"const _: () = assert!(same(COMMAND_NAMES[{COMMANDS.index(c)}].to_bytes(), b\"{c}\"));")
    out.append("// Extension names")
    for rs, name in EXTENSIONS.items():
        assert name in exts, name
        out.append(f"const _: () = assert!(same({rs}.to_bytes(), b\"{name}\"));")
    open(out_path, "w").write("\n".join(out) + "\n")
    print(f"wrote {out_path}: {len(STRUCTS)} structs, {len(stypes)} sTypes, {len(CONSTANTS)} constants, "
          f"{len(COMMANDS)} commands, {len(EXTENSIONS)} names")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
